# Generated by Django 5.1.2 on 2024-11-17 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('H_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='medicines',
            new_name='medicine',
        ),
    ]
