# Generated by Django 5.1.2 on 2024-11-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H_App', '0005_prescription_appointment_alter_prescription_dosage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
