# Generated by Django 5.1.2 on 2024-11-18 09:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H_App', '0008_prescriptionmedicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='date_prescribed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
