# Generated by Django 5.1.2 on 2024-11-18 10:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H_App', '0011_alter_prescription_appointment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='appointment_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
