# Generated by Django 5.1.2 on 2024-11-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H_App', '0012_alter_prescription_appointment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='afternoon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='evening',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='morning',
            field=models.BooleanField(default=False),
        ),
    ]
