# Generated by Django 5.1.2 on 2024-11-18 13:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H_App', '0014_remove_prescription_appointment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='date_prescribed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
