# Generated by Django 5.1.2 on 2024-11-18 15:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H_App', '0016_alter_prescription_date_prescribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='date_prescribed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
