# Generated by Django 5.1.2 on 2024-11-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H_App', '0017_alter_prescription_date_prescribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='date_prescribed',
            field=models.DateField(auto_now_add=True),
        ),
    ]
