# Generated by Django 5.1.2 on 2024-11-19 09:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H_App', '0020_alter_appointment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorslot',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
